FROM python:3.11-alpine3.19

WORKDIR /app

COPY ./cert/ /app/cert/
COPY ./processing /app/processing
COPY ./check.py /app/
COPY ./requirements.backend.txt /app/requirements.txt

RUN apk update
RUN apk add poppler
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./check.py" ]