version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - 443:443
    environment:
      - TOKEN=lYHDhUpXoGjt5j0Aj7EA3hKOKxuyKfqRzqtJWxSW4oFA5DZ3XIyEHcq8oCkLxMFG
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - 3000:3000
    environment:
      - TOKEN=lYHDhUpXoGjt5j0Aj7EA3hKOKxuyKfqRzqtJWxSW4oFA5DZ3XIyEHcq8oCkLxMFG
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 2G
          memory-swap: 10G
