FROM python:3.12-alpine3.19

WORKDIR /app

COPY ./cert/ /app/cert/
COPY ./processing /app/processing
COPY ./check.py /app/
COPY ./requirements.txt /app/

RUN pip install --no-cahce-dir -r requirements.txt

CMD [ "python", "./check.py" ]