FROM python:3.11-slim

WORKDIR /app

COPY ./requirements.frontend.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./cert/ /app/cert/
COPY ./static /app/static
COPY ./templates /app/templates
COPY ./main.py /app/

CMD [ "python", "./main.py" ]