FROM python:3.11-slim

WORKDIR /app

COPY ./cert/ /app/cert/
COPY ./processing /app/processing
COPY ./check.py /app/
COPY ./requirements.backend.txt /app/requirements.txt

RUN apt update && apt upgrade -y
RUN apt install poppler-utils -y
RUN apt-get install -y libgl1-mesa-dev -y
RUN pip install --no-cache-dir -r requirements.txt

CMD [ "python", "./check.py" ]